version: '3.8'

services:
  php:
    build: .
    container_name: leroy-php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: leroy-mysql
    restart: always
    environment:
      MYSQL_DATABASE: proyecto
      MYSQL_ROOT_PASSWORD: ''  # Contraseña vacía
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: